// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'tables.dart';

part 'app_database.g.dart';

/// The app's local database.
///
/// Opened lazily: nothing blocks the first frame on it. Pass an executor to
/// open a different database — an in-memory one, in tests.
@DriftDatabase(tables: <Type>[Items])
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor])
    : super(executor ?? driftDatabase(name: databaseName));

  /// The file the database lives in, under the app's own directory.
  static const String databaseName = 'my_app';

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (migrator) => migrator.createAll(),
    onUpgrade: (migrator, from, to) async {
      // Every step from an older schema to this one goes here, one `if` per
      // version. An upgrade with nothing to do is stated, not assumed.
      throw UnsupportedError(
        'No migration from schema $from to $to. Add one before shipping '
        'schemaVersion $to.',
      );
    },
    beforeOpen: (details) async {
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );

  /// Everything in the example table, newest first, as a live query.
  Stream<List<Item>> watchItems() =>
      (select(items)..orderBy(<OrderingTerm Function($ItemsTable)>[
            (row) => OrderingTerm.desc(row.createdAt),
          ]))
          .watch();

  Future<int> addItem({required String title, String? body}) =>
      into(items)
          .insert(ItemsCompanion.insert(title: title, body: Value(body)));

  Future<bool> setDone(int id, {required bool done}) async {
    final updated = await (update(items)..where((row) => row.id.equals(id)))
        .write(ItemsCompanion(done: Value(done)));
    return updated > 0;
  }
}

/// The database of the running app. Closed with the provider scope.
final appDatabaseProvider = Provider<AppDatabase>((ref) {
  final database = AppDatabase();
  ref.onDispose(database.close);
  return database;
});
