// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:drift/drift.dart';

/// Replace this with the app's own tables.
///
/// Every change here is a schema change: raise `AppDatabase.schemaVersion` and
/// say in `migration` what happens to a database that already exists.
class Items extends Table {
  IntColumn get id => integer().autoIncrement()();

  TextColumn get title => text().withLength(min: 1, max: 200)();

  TextColumn get body => text().nullable()();

  BoolColumn get done => boolean().withDefault(const Constant(false))();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}
