// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

/// Encrypted key-value storage, for client-side secrets only.
///
/// Tokens and nothing else. Settings belong in preferences, and records belong
/// in the database: this store is slow, small, and backed up differently on
/// each platform.
class SecureStore {
  SecureStore(this._storage);

  final FlutterSecureStorage _storage;

  Future<String?> read(String key) => _storage.read(key: key);

  Future<void> write(String key, String value) =>
      _storage.write(key: key, value: value);

  Future<void> delete(String key) => _storage.delete(key: key);

  /// Everything this app stored. Called when a session ends for good.
  Future<void> deleteAll() => _storage.deleteAll();
}

final secureStoreProvider = Provider<SecureStore>(
  (ref) => SecureStore(const FlutterSecureStorage()),
);
