// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:my_app/core/storage/database/app_database.dart';

void main() {
  // Native sqlite3, in memory: no plugin, no file, nothing left behind.
  late AppDatabase database;

  setUp(() => database = AppDatabase(NativeDatabase.memory()));
  tearDown(() => database.close());

  group('AppDatabase', () {
    test('creates the current schema on a fresh database', () async {
      await database.customSelect('SELECT 1').get();

      expect(database.schemaVersion, 1);
      expect(await database.select(database.items).get(), isEmpty);
    });

    test('writes and reads through the generated API', () async {
      final id = await database.addItem(title: 'First', body: 'Hello');

      final items = await database.select(database.items).get();
      expect(items, hasLength(1));
      expect(items.single.id, id);
      expect(items.single.done, isFalse);

      expect(await database.setDone(id, done: true), isTrue);
      final updated = await database.select(database.items).getSingle();
      expect(updated.done, isTrue);
    });

    test('foreign keys are enforced', () async {
      final result = await database
          .customSelect('PRAGMA foreign_keys')
          .getSingle();

      expect(result.data.values.first, 1);
    });
  });
}
